name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8           
  - pandas            
  - numpy             
  - nltk              
  - spacy
  - scikit-learn
  - seaborn
  - jupyter
  - jupyterlab
  - gensim
  - pip                 
  - pip:
      - allennlp     